name: Build Docker Images

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to UHub
      uses: docker/login-action@v2
      with:
        registry: uhub.service.ucloud.cn
        username: ${{ secrets.UHUB_USER }}
        password: ${{ secrets.UHUB_PASSWORD }}

    - name: Build images
      run: make docker-build DOCKER_CMD="docker"
