name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to UHub
      uses: docker/login-action@v2
      with:
        registry: uhub.service.ucloud.cn
        username: ${{ secrets.UHUB_USER }}
        password: ${{ secrets.UHUB_PASSWORD }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5

    - name: Build ipamd
      run: DEPLOY=true make ipamd

    - name: Build vip-controller
      run: DEPLOY=true make vip-controller

    - name: Build cni
      run: make cni

    - name: Package cni
      run: >
        tar -cv
        LICENSE README.md
        -C bin/ cnivpc cnivpctl
        | gzip --best
        > 'uk8s-cni-vpc_${{ steps.get_version.outputs.VERSION }}.tar.gz'

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          *.tar.gz
